version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      - CLICKHOUSE_DB=analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=root
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  clickhouse-data: